import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
# startup_mode = "fullscreen"
dimensions.columns = 250
dimensions.lines = 60

decorations = "Buttonless"

opacity = 0.5
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 12
