[ env ]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
# startup_mode = "fullscreen"
dimensions.columns = 300
dimensions.lines = 60

# decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 12

[general]

import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
