# Use the latest Ubuntu image as the base
FROM abhishek1009/ubuntu:latest

# Set non-interactive mode for APT
ENV DEBIAN_FRONTEND=noninteractive
# Update package lists and install required packages
# install java21, python, nodejs, npm, golang, rust, zig, scala
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    software-properties-common \
    curl \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y \
    openjdk-25-jdk \
    python3 \
    python3-pip \
    python3.12-venv \
    nodejs \
    npm \
    golang \
    rustc \
    scala \
    maven \
    gradle \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"
# Set the default shell to zsh
SHELL ["/bin/zsh", "-c"]
# Set the default command to zsh
CMD ["zsh"]
# Set the working directory
WORKDIR /workspace

# EXPOSE 8080-9090
EXPOSE 5000-9000