# Use the latest Ubuntu image as the base
FROM abhishek1009/sandbox:latest

# Set non-interactive mode for APT
ENV DEBIAN_FRONTEND=noninteractive
# Update package lists and install required packages
# install java21, python, nodejs, npm, golang, rust, zig, scala
RUN apt-get update && apt-get install -y \
    openjdk-21-jdk \
    python3 \
    python3-pip \
    nodejs \
    npm \
    golang \
    rustc \
    scala \
    maven \
    gradle \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Set the default shell to zsh
SHELL ["/bin/zsh", "-c"]
# Set the default command to zsh
CMD ["zsh"]
# Set the working directory
WORKDIR /workspace

# EXPOSE 8080-9090
EXPOSE 5000-9000