site_name: dotfiles
site_url: https://abhishekghoshh.github.io/dotfiles/

nav:
  - Home: index.md
  - git:
    - introduction: git/introduction.md
    - configurations: git/configurations.md
    - cloning: git/cloning.md
    - initialization: git/intialization.md
    - modifying files: git/modifying_files.md
    - project status: git/project_status.md
    - logs: git/logs.md
    - commits: git/commits.md
    - branching: git/branching.md
    - pull and synchronize: git/pull_and_synchronize.md
    - push: git/push.md
    - rebase: git/rebase.md
    - tagging: git/tagging.md
    - advanced: git/advanced.md
  - linux:
    - commands: linux/commands.md
  - shortcuts:
    - typing: shortcuts/typing.md
    - command line: shortcuts/command-line.md
  - tmux: tmux.md
  - nvim:
    - vim: nvim/vim.md
  - other links:
    - typing: links/typing.md
    - git: links/git.md


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/abhishekghoshh
    - icon: fontawesome/brands/twitter
      link: https://x.com/abhishek_ghoshh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abhishek-ghosh-220679132/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: |
  &copy; 2025 <a href="https://github.com/abhishekghoshh"  target="_blank" rel="noopener">Abhishek Ghosh</a>